version: '3.9'

services:
  ucedockets:
    image: pcms.ucedockets

    # NOTE: running the container as root simplifies getting
    # a demo up and running quickly, but is not a great idea
    # in production. the container is configured to run
    # as UID:5678 but needs read/write access to storage
    # for syncronizing files and creating a database and
    # running in lower privileges with more deliberate
    # storage mappings is a better plan than the this demo
    user: root

    # environment:
      # Configuration Precedence:
      #   UCEDocketsOptions.cs < appsettings.json < ./config/config.json < EnvVar

      # SECURITY NOTE: this will work, and may be appropriate for production, but beware
      # that this file is under source control and in a public repo.
      # please do not accidentally commit your credentials.
      #    if you just did, treat them as publicly leaked. Immediately contact OCA to change them.
      # - UCEDockets__SFTP__Username=USERNAME
      # - UCEDockets__SFTP__Password=PASSWORD

    volumes:
       - ./data/sync:/data/sync
       - ./data/db:/data/db
       - ./config:/app/config
    build:
      context: .
      dockerfile: ./src/PCMS.UCEDockets/Dockerfile
    ports:
      - 5023:5023