version: '3.9'

services:
  ucedockets:
    image: pcms.ucedockets
    # environment:
      # Configuration Precedence:
      #   UCEDocketsOptions.cs < appsettings.json < ./config/config.json < EnvVar
    volumes:
       - ./data/sync:/data/sync
       - ./data/db:/data/db
       - ./config:/app/config
    build:
      context: .
      dockerfile: ./src/PCMS.UCEDockets/Dockerfile
    ports:
      - 5023:5023