// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCMS.UCEDockets.Entities;

#nullable disable

namespace PCMS.UCEDockets.Migrations
{
    [DbContext(typeof(UCEDocketsContext))]
    partial class UCEDocketsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("PCMS.UCEDockets.Entities.Docket", b =>
                {
                    b.Property<string>("DocketID")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("County")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Filed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("XMLDocket")
                        .HasColumnType("TEXT");

                    b.HasKey("DocketID");

                    b.ToTable("Dockets");
                });
#pragma warning restore 612, 618
        }
    }
}
